### ISSUE TITLE
Add spinner 

### ISSUE THREAD

**Issue by anu-shree** [intermine/bluegenes-go-concept-relation#10]
I would like to add spinner instead of the "**Loading...**" text.

Can I work on this?

![Screen Shot 2020-03-16 at 11 06 45 AM](https://user-images.githubusercontent.com/40749928/76728179-02467900-677c-11ea-97b8-a39f241fe204.png)

**Comment by akshatbhargava123** [comment]
Hey @anu-shree #9 already has this change. Thanks for noticing the issue though!
