### ISSUE TITLE
Update demo.html with ids and use them

### ISSUE THREAD

**Issue by uosl** [intermine/bluegenes-go-concept-relation#11]
In [this](https://github.com/intermine/bluegenes-go-concept-relation/blob/5de3f8bfcad9d66cd941d3ab7c884a5a369b51a1/demo.html#L51) part of demo.html, we'll want to update `format` to `ids` and `value` to an array of numbers of [these](https://github.com/intermine/bluegenes-go-concept-relation/blob/5de3f8bfcad9d66cd941d3ab7c884a5a369b51a1/src/RootContainer.js#L10). Finally, make sure that `entity` (as passed in index.js) is used in the RootContainer, instead of the hardcoded values.

This is necessary for the visualizer to use the values passed by Bluegenes.

**Comment by Sakshisrivastava413** [comment]
I would like to work on this issue.

**Comment by uosl** [comment]
@Sakshisrivastava413 Please go ahead!
