### ISSUE TITLE
Show tooltip on node click or hover

### ISSUE THREAD

**Issue by uosl** [intermine/bluegenes-go-concept-relation#4]
Clicking or hovering over a gene or GO term should open a tooltip (or perhaps a window adjacent to the graph) with additional data on that gene or GO term.

Check the data returned by the existing query which is used to produce the GO terms. It should contain additional data on the GO term which you can display in the tooltip.
To also get a description of the GO term, add `goAnnotation.ontologyTerm.description` as an additional `select` (see `src/query.js`).

For the tooltip for a gene node, the following keys can be enough to begin with: 'id','symbol','secondaryIdentifier','primaryIdentifier','organism.shortName'. They should already be present in the query.

Note: I will assign this to @Sakshisrivastava413 as she approached me about this feature first.

**Comment by Sakshisrivastava413** [comment]
I would like to work on this issue. Thanks for the mentions. :)
