### ISSUE TITLE
Display GO term name besides nodes

### ISSUE THREAD

**Issue by uosl** [intermine/bluegenes-go-concept-relation#7]
On the yellow nodes that signify GO (gene ontology) terms, we should show the name instead of the symbol (ie. *fatty acid binding* instead of GO:0005504)

![2020-03-13-152956_157x130_scrot](https://user-images.githubusercontent.com/3865590/76635516-83fd9300-653f-11ea-93c9-f98d8e0d7da4.png)

**Comment by dmahajan980** [comment]
Hello @uosl! I would like to work on this issue :)

**Comment by uosl** [comment]
Please go ahead [=

**Comment by uosl** [comment]
We decided to show no labels at all instead: #19
