### ISSUE TITLE
Add Ontology filter

### ISSUE THREAD

**Issue by uosl** [intermine/bluegenes-go-concept-relation#8]
Similar to the below image from [bluegenes-GO-term-visualizer](https://github.com/intermine/bluegenes-GO-term-visualizer), except with only the *Ontology* filter, so it can probably be made more compact.

What this filter should do, is allow you to select one specific ontology, so that only the query results which have this ontology will be displayed (log the results of running the query in this repo if you're not sure what this means).

![](https://raw.githubusercontent.com/intermine/bluegenes-GO-term-visualizer/master/preview.png)

**Comment by Sakshisrivastava413** [comment]
I would like to work on this issue.

**Comment by uosl** [comment]
Please go ahead [=

**Comment by Sakshisrivastava413** [comment]
What I understood is that we need a searchable dropdown with the list of genes symbol that we get from the query. User can select multiple genes according to their requirement and only selected gene would be displayed along with its children. This will create visualization much cleaner and understandable.

**Comment by uosl** [comment]
Hmm, that doesn't sound quite right. I recommend you clone https://github.com/intermine/bluegenes-GO-term-visualizer and run it, then play around with the ontology filter dropdown. Then you check the response to the query in this repo (either via the browser devtool network panel, or adding a console.log in the code) and see how it relates. Hopefully it will make sense then!
